### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by norefer** [mtl1979/bittorium-webwallet#1]
thanks for this, get error:
Caught exception while opening database: Unable to open database: unable to open database file

i created database ad get correct path but still error

how to solve?

**Comment by mtl1979** [comment]
The data/db directory needs to belong to group "www-data" with mode 2770, otherwise sqlite3 can't access the file. It doesn't matter who owns the directory, only the group matters. If you create the database file yourself, you need to make sure "www-data" group has both read and write permissions (mode 0660).

**Comment by norefer** [comment]
ok thank you for reply, i wil try and let you know if everythings works.
many thanks

**Comment by mtl1979** [comment]
I will write full installation instructions later...

**Comment by norefer** [comment]
assigned it "2770" as you say, also checked if the dir data have the www-data group manage the dir but get same error :/

root@vmi235251:~# getfacl /var/www/html/data/
getfacl: Removing leading '/' from absolute path names
# file: var/www/html/data/
# owner: www-data
# group: www-data
# flags: -s-
user::rwx
group::rwx
other::---

regards

**Comment by mtl1979** [comment]
The permissions should be
```
root@pool /webwallet # ls -la data/db
total 12
drwxrws--- 2 root www-data 4096 Jan  8 17:42 .
drwxrwxrwx 3 root root     4096 Jan  8 18:19 ..
-rwxrwx--- 1 root www-data 2048 Jan  8 17:42 database.db
```

**Comment by norefer** [comment]
yes mine looks like this:

root@vmi235251:/var/www/html# ls -la data/db
total 16
drwxrws--- 2 www-data www-data 4096 Jan  8 17:51 .
drwxrws--- 3 www-data www-data 4096 Jan  8 13:49 ..
-rwxrwx--- 1 www-data www-data 8192 Jan  8 13:29 database.db

**Comment by mtl1979** [comment]
Did you change the path in ```lib/database.php```?

**Comment by norefer** [comment]
yes, looks like i solved the issue with it, got message of create database and table users correctly, now get this, probably not connect correctly with the daemon i will check in it

Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/html/lib/daemon.php:29 Stack trace: #0 /var/www/html/lib/database.php(112): walletrpc_post('getViewKey') #1 /var/www/html/index.php(30): check_database() #2 {main} thrown in /var/www/html/lib/daemon.php on line 29

**Comment by mtl1979** [comment]
You need php-curl and  php-sqlite3 packages for it to work...

**Comment by norefer** [comment]
yes ofc, i have both installed on php 7.0, i using ubuntu 16.4

**Comment by norefer** [comment]
ok solved by restarting the apache thank you

**Comment by norefer** [comment]
hello, everythings working very well i just have an issue with the fee i try to change many things but is always 0.00000001 where can edit it which file and line? 
thanks

**Comment by norefer** [comment]
hello i find a bug with the amount in the transaction, if you send transaction to external wallet it show correct, but if you send transaction from webwallet to webwallet the on the amount row show the fee not the ream amount sended or received? any advice how to solve this bug?

**Comment by mtl1979** [comment]
@norefer Because the different accounts on webwallet are subaddresses of same wallet (same view key, different spend key), blockchain can't track sent amounts. As long as account balances reflect the transaction correctly, there is little I can fix. You should take a screenshot of the transaction details page on both wallets to see what it actually records in the blockchain.

**Comment by norefer** [comment]
@mtl1979  hi, you are right both wallet have same view key

there is address of the transaction dettails:

webwallet 1
NTegwAJnXeapfX1Ui7FMQ6j4b1N6Zv7wHgAGeDEVVBfDNn7qpuN1XP8PMXoSaYtF4ZzALm4233doEpFKJckKmfV2f9kdqY6KX

webwallet 2
NTep7gjUk8XKwNdZ3tTWT7P71h8WPdCZ8HkADGnAmG41cLFuKuu5tD8PMXoSaYtF4ZzALm4233doEpFKJckKmfV2f9keaZheU

webwallet 1
NTegwAJnXeapfX1Ui7FMQ6j4b1N6Zv7wHgAGeDEVVBfDNn7qpuN1XP8PMXoSaYtF4ZzALm4233doEpFKJckKmfV2f9kdqY6KX

webwallet "unknow"
NTf1o4p9tUXHncez2E2eiWiRQVuEuk5rco9ykyv1MR9NqE1fWR7Tcd8PMXoSaYtF4ZzALm4233doEpFKJckKmfV2f9kgpvhJ4

webwallet 2
NTep7gjUk8XKwNdZ3tTWT7P71h8WPdCZ8HkADGnAmG41cLFuKuu5tD8PMXoSaYtF4ZzALm4233doEpFKJckKmfV2f9keaZheU


any advice how to fix? thanks

**Comment by mtl1979** [comment]
@norefer In technical sense, the webwallet's daemon (walletd) is sending coins to itself, hence zero sum transfer. There isn't much I can fix as it's property of CryptoNote protocol (transactions are viewed using private view key, which is same for all addresses inside same wallet file).

The reason why the webwallet doesn't show all transactions for everyone is that it uses both public keys to filter the transactions (public keys are stored in transfer metadata). In RPC code it passes the wallet's address to walletd whenever it needs to access coins sent to one of the subaddresses. 

walletd automatically converts the wallet address to public view and spend keys, or private spend key. It's possible to get both public and private view key by passing nothing to walletd as it defaults to the first address in container.

**Comment by norefer** [comment]
ok thanks for the clarifications

**Comment by mtl1979** [comment]
There is a risk that if I change that it recalculates the real amount from individual transfers by comparing the current wallet address, it would time out when there is a lot of transactions as it needs to load all of them before reversing the order and counting maximum of 20 transactions. BTW... I updated the whole database schema for latest update, so if you want to use it, you need to dump the users table, delete it and reimport the dump. Now it doesn't need hack when reading authentication code in users table or payment ID in contacts table. Old schema did try to convert those two to numbers and managed to confuse PHP when reading back.

**Comment by norefer** [comment]
hello, you know why after 10 days some balance on different wallets are disappeared? it show 0 is weird because is full synched and the daemon running correctly..
any idea? i also try to resync the walletd from 0 but nothing

**Comment by mtl1979** [comment]
You should check the walletd log... When I tested, it sometimes did reset the wallet file automatically after new address was added, it would take up to 7 minutes before it did show correct balance depending on CPU speed. 

You should also monitor how much physical memory it uses, if it hits too high, it will flush the data to disk but fail to reload it when needed. It does not use swap even if available, because it uses memory-mapped I/O to access the wallet file. I did run the webwallet with 8 GB physical memory just to see how high the memory usage peaked.

**Comment by norefer** [comment]
thank you for fast reply, no i don't thing is this the problem because using 32gb of physical memory, actualy i try again to sync to zero but now when try to run the walletd it say failed to read wallet version.. no idea why doing this now

**Comment by mtl1979** [comment]
@norefer It means it can't read the wallet file... Either another process has locked the file or it is corrupted.

**Comment by norefer** [comment]
solved thanks, but still not recovered all the lost balances :/

**Comment by mtl1979** [comment]
@norefer That's why I said the walletd logs contain clues to the lost/wrong balances... It's always essential to redirect the output of both daemons to a file (or stdout and stderr to separate files).
